# Generated by Django 4.1 on 2022-08-27 14:31

import apps.courses.models.courses
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.courses.models.courses.upload_location)),
                ('teacher_image', models.ImageField(upload_to=apps.courses.models.courses.upload_location)),
                ('teacher', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('price', models.CharField(max_length=255)),
                ('lessons_amount', models.CharField(max_length=255)),
                ('teacher_level', models.CharField(max_length=255)),
                ('lesson_duration', models.CharField(max_length=255)),
            ],
        ),
    ]
