# Generated by Django 4.1 on 2022-08-30 06:28

import apps.courses.models.facts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.courses.models.facts.upload_location)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('graduates', models.CharField(max_length=55)),
                ('employment', models.CharField(max_length=55)),
                ('salary', models.CharField(max_length=55)),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.courses.models.facts.upload_location)),
            ],
        ),
    ]
