# Generated by Django 4.1 on 2022-12-27 11:58

import apps.about_us.models.about_us
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_aboutusmodel_image1_alter_aboutusmodel_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='image1',
            field=models.ImageField(upload_to=apps.about_us.models.about_us.upload_location),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='image2',
            field=models.ImageField(upload_to=apps.about_us.models.about_us.upload_location),
        ),
    ]
