# Generated by Django 4.1 on 2022-11-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachermodel_rating_teachermodel_teacher_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='teacher_level',
            field=models.CharField(choices=[('Junior', 'Junior')], max_length=255),
        ),
    ]
