# Generated by Django 4.1 on 2022-08-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('social_network1', models.URLField(blank=True, max_length=255, null=True)),
                ('social_network2', models.URLField(blank=True, max_length=255, null=True)),
                ('social_network3', models.URLField(blank=True, max_length=255, null=True)),
                ('social_network4', models.URLField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=155)),
            ],
        ),
    ]
