# Generated by Django 4.1 on 2022-11-04 07:29

import apps.partners.models.partners
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.partners.models.partners.upload_location),
        ),
    ]
